### ISSUE TITLE
Create a new model for documentation of the framework

### ISSUE THREAD

**Issue by rodgeraraujo** [rodgeraraujo/minus.css#8]
### Description
After creating the new structure (from this issue #7), we will need a new model to describe the components and code samples.

Suggestions are welcome.

**Comment by youngkaneda** [comment]
I guess we should use storybook for this, after get the linked issue, I can do this too.

**Comment by rodgeraraujo** [comment]
Excelent idea. If you can work on it, it would be of great help.
